import { Category, Cuisine, Diet, Occasion, Profile } from "@prisma/client";

export const profiles: Profile[] = [
  {
    id: "8e5cc3b3-ceaa-446c-a965-dd88086daf59",
    name: "Chat GPT",
    bio: "All of the recipes are generated by GPT-3.",
    email: "miloszkrainsky@gmail.com",
    image: null,

    emailVerificationToken: null,
    emailVerified: true,

    hashedPassword: "132",
    resetPasswordToken: null,
    resetPasswordTokenExpiry: null,

    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const categories: Category[] = [
  {
    id: "0dbc07ca-197a-463c-a9c3-8a1d06256eb4",
    slug: "salatki",
    name: "Sałatki",
    image:
      "https://images.pexels.com/photos/15913452/pexels-photo-15913452/free-photo-of-jedzenie-zdrowy-warzywa-posilek.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    updatedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "26c5ff35-514c-4dbb-8887-c0101e8f90a3",
    slug: "przetwory",
    name: "Przetwory",
    image:
      "https://images.pexels.com/photos/15913452/pexels-photo-15913452/free-photo-of-jedzenie-zdrowy-warzywa-posilek.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    updatedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "284dbed2-b9e3-4d74-b631-3058fc48ae40",
    slug: "napoje",
    name: "Napoje",
    image:
      "https://images.pexels.com/photos/15913452/pexels-photo-15913452/free-photo-of-jedzenie-zdrowy-warzywa-posilek.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    updatedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "68127b54-8880-4b65-bf00-566c6712bc35",
    slug: "dania-glowne",
    name: "Dania główne",
    image:
      "https://images.pexels.com/photos/15913452/pexels-photo-15913452/free-photo-of-jedzenie-zdrowy-warzywa-posilek.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    updatedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "720f659b-0daa-4a33-bda1-8473a6a6f7bf",
    slug: "desery",
    name: "Desery",
    image:
      "https://images.pexels.com/photos/15913452/pexels-photo-15913452/free-photo-of-jedzenie-zdrowy-warzywa-posilek.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    updatedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "7eb80b42-3dd5-4d32-b93b-9ea42b03b6c5",
    slug: "pieczywo",
    name: "Pieczywo",
    image:
      "https://images.pexels.com/photos/15913452/pexels-photo-15913452/free-photo-of-jedzenie-zdrowy-warzywa-posilek.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    updatedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "816d364a-cf68-46d5-af6a-1c80a040e84c",
    slug: "zupy",
    name: "Zupy",
    image:
      "https://images.pexels.com/photos/15913452/pexels-photo-15913452/free-photo-of-jedzenie-zdrowy-warzywa-posilek.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    updatedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "9f91b46c-498a-457b-81dc-1cea2614eec4",
    slug: "sniadania",
    name: "Śniadania",
    image:
      "https://images.pexels.com/photos/15913452/pexels-photo-15913452/free-photo-of-jedzenie-zdrowy-warzywa-posilek.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    updatedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "bba9d101-9467-432a-8b89-7a1657d277b9",
    slug: "przekaski",
    name: "Przekąski",
    image:
      "https://images.pexels.com/photos/15913452/pexels-photo-15913452/free-photo-of-jedzenie-zdrowy-warzywa-posilek.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    updatedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "c9497db2-c648-46f6-b942-4ba2cdc70041",
    slug: "wedliny",
    name: "Wędliny",
    image:
      "https://images.pexels.com/photos/15913452/pexels-photo-15913452/free-photo-of-jedzenie-zdrowy-warzywa-posilek.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    updatedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: "f0ac28c8-d999-43aa-8325-c5f419b09fef",
    slug: "dodatki",
    name: "Dodatki",
    image:
      "https://images.pexels.com/photos/15913452/pexels-photo-15913452/free-photo-of-jedzenie-zdrowy-warzywa-posilek.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    updatedAt: new Date(),
    createdAt: new Date(),
  },
];

export const occasions: Occasion[] = [
  {
    id: "15caf680-0399-4ad4-b155-70915fc7f87a",
    name: "Do pracy",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4916a222-69f7-4c83-a059-8dbc4eb96f20",
    name: "Boże narodzenie",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "6c475c17-5912-4ab4-8b93-ebfdacf6248a",
    name: "Grill",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "7841ef74-c19e-42fa-ae83-cab63b5902a2",
    name: "Halloween",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "914ea8e4-6078-4823-b703-5ae6443bfc31",
    name: "Walentynki",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "a718a654-fc0f-4ac0-afc2-c010bc6e7e65",
    name: "Impreza",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "d7d64bdf-8497-433b-b726-1c17705f51c3",
    name: "Tłusty czwartek",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "dc011e9b-5bc0-4b6b-b35e-15af5efdda1a",
    name: "Wielkanoc",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "f7de17f2-5dbd-4df5-86d6-69c5ef3acf03",
    name: "Komunia",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const cuisines: Cuisine[] = [
  {
    id: "01be4f9d-2511-43e2-b357-0188718dd521",
    name: "Żydowska",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "08af99ba-c599-4f2f-b7cd-827774bff569",
    name: "Tajska",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "12be8dcf-15e5-4926-bc99-77f851d6ea72",
    name: "Chińska",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "137e2326-aff4-4a89-9d55-903464cb603c",
    name: "Czeska",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "15243899-a4f0-4afc-88af-438f108d4e81",
    name: "Włoska",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2a9a5bb5-5835-4094-8924-3fd840aee7b4",
    name: "Meksykańska",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "34a6757c-99f2-4f0c-b990-89e0275ab82b",
    name: "Ukraińska",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "5b3cf647-71fb-4258-bbcf-a5a4d4a9162d",
    name: "Grecka",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "5c305c34-8fa8-477c-a4dd-500816e879c1",
    name: "Francuska",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "8364e68c-f35a-42ca-825e-9ede07022cba",
    name: "Polska",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "8b2beaff-3bbc-42ad-8ba6-03a8467c55f4",
    name: "Węgierska",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "9718a3ee-7c41-482b-81ac-c1e3007b1ddf",
    name: "Indyjska",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "b517978f-4261-4432-b81f-e31bec5584dc",
    name: "Bałkańska",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "d0b2f680-0bd9-42ca-96b2-359b5ed989b6",
    name: "Azjatycka",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "e9677434-69af-4a2b-9859-3bbfdf0d1f8e",
    name: "Śródziemnomorska",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "ee96b1c0-0c5a-4fa5-abd6-3fc599dd4f1b",
    name: "Amerykańska",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const diets: Diet[] = [
  {
    id: "20798824-3b33-40d3-8676-d83c318244ce",
    name: "Bez glutenu",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3f53015e-78cc-47ae-9e63-d35e64ca237e",
    name: "Dla dzieci",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3ffb5397-438f-476c-95bb-7902fe8aaf8b",
    name: "Bez laktozy",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "5cb0d888-efd8-4193-b337-fb6d3f84aacf",
    name: "Dla zdrowia",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "64291830-3d24-4692-b126-23942f7ce6a9",
    name: "Bez cukru",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "7d7a8b9b-9267-4c08-ab1c-6fda337cc6e7",
    name: "Wegetariańskie",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "98931559-b002-4a37-8a44-05510bd7dd89",
    name: "Wegańskie",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "9e4601bc-51e9-4547-8db0-a71b3deeb9f4",
    name: "Dietetyczne",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "b1df4911-f2c1-41fe-8bd3-1b096ce44615",
    name: "Ketogeniczne",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
